# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bMkR_UPS5anPJqVc48LoeR5kyMFnyn_P

# Distance Calculator

## Description
This program calculates the distance between two points using their x and y coordinates

## How to Run
1. Open the program
2. Run the program
3. Enter the required coordinates

## nput Needed
-x and y coordinates

## Sample Output
The distance between two points is 7.07

## Author
Name: Lia Sofie O. Losañes
Section: Acacia
"""